display_name: VenturaVPN
package_name: venturavpn
maintainer:
  name: venturavpn
  email: venturavpn@gmail.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: assets/images/source/ic_launcher_border.png

# Post-installation tasks:
# 1. Inject StartupWMClass into the system .desktop file for correct icon association
# 2. Remove conflicting venturavpn.desktop files from users' .local directories (cleanup AppImage artifacts)
# 3. Update the desktop database to apply changes immediately
postinstall_scripts:
  - echo "Setting up VenturaVPN..."
  - sudo sed -i '/^\[Desktop Entry\]/a StartupWMClass=com.venturavpn.app' "/usr/share/applications/venturavpn.desktop"
  - echo "Search and remove venturavpn.desktop from .local"
  - for user_dir in /home/*; do if [ -f "$user_dir/.local/share/applications/venturavpn.desktop" ]; then rm -f "$user_dir/.local/share/applications/venturavpn.desktop"; echo "Found and removed hiddify.desktop from $user_dir .local"; fi; done
  - update-desktop-database /usr/share/applications
  - echo "VenturaVPN is ready to use :)"

# Post-uninstallation tasks:
# 1. Iterate through all user directories to remove VenturaVPN configuration and data
# 2. Clean up root user data to ensure a clean removal
postuninstall_scripts:
  - echo "Removing VenturaVPN user data..."
  - for user_dir in /home/*; do if [ -d "$user_dir/.local/share/venturavpn" ]; then rm -rf "$user_dir/.local/share/venturavpn"; echo "Removed data from $user_dir"; fi; done
  - rm -rf /root/.local/share/venturavpn
  - echo "VenturaVPN data cleanup complete."

keywords:
  - Hiddify
  - Proxy
  - VPN
  - V2ray
  - Nekoray
  - Xray
  - Psiphon
  - OpenVPN

generic_name: VenturaVPN

categories:
  - Network

startup_notify: true
# app_links setup for Linux
# https://github.com/llfbandit/app_links/blob/master/doc/README_linux.md
supported_mime_type:
  - x-scheme-handler/venturavpn
  - x-scheme-handler/v2ray
  - x-scheme-handler/v2rayn
  - x-scheme-handler/v2rayng
  - x-scheme-handler/clash
  - x-scheme-handler/clashmeta
  - x-scheme-handler/sing-box

metainfo: linux/packaging/com.venturavpn.app.appdata.xml
